### PR TITLE
Issue #9: Generating "export class" without module/namespace

### PR DESCRIPTION
**Pull request by ysavoie-lavigueur**
Fixes related issue: #20

### CODE REVIEW

**Comment by pavel-b-novikov** [comment]
Hold on, please. I see your pull request, but do not have enough time to review now.

**Comment by pavel-b-novikov** [comment]
I will review next week: right now I'm experiencing some dfficulties with relocation from one county to another. Dont miss me

**Comment by pavel-b-novikov** [comment]
Why did you remove ```if (prev == WriterContext.Module)``` ? In case of appearing "export" outside of module - it causes error. No?

**Comment by ysavoie-lavigueur** [comment]
Hi, thanks for taking the time to review my PR.

As far as I know, a module (namespace) is not required to export classes/interface/variables. See the examples listed in the Typescript documentation (https://www.typescriptlang.org/docs/handbook/modules.html).
I think exports outside of modules is used extensively in some SPA frameworks (we use them in an Angular2 app for example).

**Comment by pavel-b-novikov** [comment]
Yes, I have seen. But the thing is that AFAIK it works in TypeScript >= 1.8 
I clearly remember that I've got error something like "export without module" on TS 1.6, so thats why this line was added. I think, here it is required more flexible solution. E.g. let user to decide when to export classes/interfaces and when dont.

**Comment by ysavoie-lavigueur** [comment]
I tried compiling an output of Reinforced.Typings that contains exported classes outside of modules with some older versions of the Typescript compiler (1.4 & 1.6). I got the error you were talking about if I did not specify any compiler options:
`error TS1148: Cannot compile modules unless the '--module' flag is provided.`

Adding the `--module 'commonjs'` compiler option fixed the error.
I think Typescript > 1.8 defaults to `--module 'commonjs'` if this option is not explicitly provided.

I don't think we should prevent users from configuring Reinforced.Typings to output exported classes outside of modules because of this error. I think it is their responsibility to configure their Typescript compiler accordingly.

**Comment by ysavoie-lavigueur** [comment]
Hi,
did you have time to look into my previous response?
Thanks

**Comment by pavel-b-novikov** [comment]
Not yet, Yoann. I remember.

**Comment by AndreyTsvetkov** [comment]
I'm also on pause waiting for the PR :) Just to let know.

**Comment by AndreyTsvetkov** [comment]
By any chance, can I help you somehow to make this PR released? For instance i can merge it and test on my own or on your instructions and give you the report of it... 

Now i have to post-process the generated .ts to remove namespaces from enums, and its a fragile solution :(

**Comment by pavel-b-novikov** [comment]
Andrey, please contact me by skype - i will explain the thing.
nsu_the_cjay

**Comment by pavel-b-novikov** [comment]
Sorry, I have to close this PR without merge because problem seems little bit bigger and it is already solved in 1.30 branch
